### ISSUE TITLE
Error building the Flutter project

### ISSUE THREAD

**Issue by federicoviceconti** [TetaBuilder/teta_widgets#1]
When I launch the "flutter pub get" on the project, I got the following error:

```
Git error. Command: git clone --mirror git@github.com:andreabuttarelli/Teta.git
stdout: 
stderr: Cloning into bare repository
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
```

Is it possible to run in other ways? Thanks for your support.

**Comment by andreabuttarelli** [comment]
Hey! 
Unfortunately, this is an abstract repo right now. 
You cannot run it yet because it depends on our internal module.

**Comment by iamEvara** [comment]
I don't understand the meaning of open source if you can't contribute, it's either a show-off or a marketing clickbait.

**Comment by andreabuttarelli** [comment]
I think this is quite exaggerated 😅 we are still looking for a way to let everyone contribute this repo, as other (e.g. Teta cms) as well 🤓
