### ISSUE TITLE
Teta loading: Teta doesn't load projects

### ISSUE THREAD

**Issue by andreabuttarelli** [TetaBuilder/teta_widgets#21]
It stops on the logo screen
Network tab: error for back.teta.so private room
- Detect what is causing this issue
- Contact Itz_Raoulpcs_, sakhildevan, and camelCasePro

**Comment by andreabuttarelli** [comment]
Worked on this on 4.0.8

**Comment by raoulpcs** [comment]
Hey,

Itz_Raoulpcs_ here, it's working for me. I can access all things.

Thanks!

**Comment by Sakhildevan** [comment]
its not working for me

**Comment by andreabuttarelli** [comment]
Fixed :) Adblockers could block some of our requests
